var namespace_m_pewsey_1_1_mania_map_unity_1_1_exceptions =
[
    [ "DuplicateInputException", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_duplicate_input_exception.html", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_duplicate_input_exception" ],
    [ "MissingInputException", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_missing_input_exception.html", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_missing_input_exception" ],
    [ "RoomNotInitializedException", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_room_not_initialized_exception.html", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_room_not_initialized_exception" ],
    [ "RoomTemplateNotInitializedException", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_room_template_not_initialized_exception.html", "class_m_pewsey_1_1_mania_map_unity_1_1_exceptions_1_1_room_template_not_initialized_exception" ]
];